[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Async-Website-Ping-Tool"
version = "0.0.1"
dependencies = [
    "httpx",
]

[project.scripts]
aping = "ping:run"